version: '3.8'
services:

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres

# volumes:
#   postgres-data: